[metadata]
format.version = "1.1"

[versions]
djl = "0.34.0"
pytorch = "2.7.1"
tensorflow = "2.16.1"
tensorflowCore = "1.0.0-rc.1"
mxnet = "1.9.1"
onnxruntime = "1.21.1"
onnxruntimeExtensions = "0.13.0"
xgboost = "2.0.3"
lightgbm = "3.2.110"
tensorrt = "8.4.1"
fasttext = "0.9.2"
sentencepiece = "0.2.0"
tokenizers = "0.21.0"

slf4j = "2.0.17"
log4j_slf4j = "2.24.3"
gson = "2.13.1"
jna = "5.14.0"
commonCli = "1.9.0"
commonsCompress = "1.27.1"
commonsCsv = "1.14.0"
commonsLogging = "1.3.5"

awssdk = "2.31.36"
ffmpeg = "7.1-1.5.11"
hadoop = "3.4.1"
javacpp = "1.5.11"
javacv = "1.5.11"
openpnpOpencv = "4.9.0-0"
spark = "3.5.5"
tablesaw = "0.44.1"
rapis = "25.02.2"
protobuf = "4.30.2"
jackson = "2.19.0"
jtransforms = "3.1"

antlr = "4.11.1"
testng = "7.11.0"
junit = "4.13.2"
mockito = "5.17.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
commons-logging = { module = "commons-logging:commons-logging", version.ref = "commonsLogging" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commonCli" }
apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
apache-hadoop-client = { module = "org.apache.hadoop:hadoop-client", version.ref = "hadoop" }
apache-hadoop-minicluster = { module = "org.apache.hadoop:hadoop-minicluster", version.ref = "hadoop" }
apache-log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j_slf4j" }
onnxruntime = { module = "com.microsoft.onnxruntime:onnxruntime", version.ref = "onnxruntime" }
onnxruntimeAndroid = { module = "com.microsoft.onnxruntime:onnxruntime-android", version.ref = "onnxruntime" }
bytedeco-javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacpp" }
bytedeco-javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }
bytedeco-ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
awssdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "awssdk" }
awssdk-s3 = { module = "software.amazon.awssdk:s3" }
openpnp-opencv = { module = "org.openpnp:opencv", version.ref = "openpnpOpencv" }
spark-core = { module = "org.apache.spark:spark-core_2.12", version.ref = "spark" }
spark-sql = { module = "org.apache.spark:spark-sql_2.12", version.ref = "spark" }
spark-mllib = { module = "org.apache.spark:spark-mllib_2.12", version.ref = "spark" }
tablesaw-core = { module = "tech.tablesaw:tablesaw-core", version.ref = "tablesaw" }
tablesaw-excel = { module = "tech.tablesaw:tablesaw-excel", version.ref = "tablesaw" }
tablesaw-html = { module = "tech.tablesaw:tablesaw-html", version.ref = "tablesaw" }
tablesaw-json = { module = "tech.tablesaw:tablesaw-json", version.ref = "tablesaw" }
tablesaw-jsplot = { module = "tech.tablesaw:tablesaw-jsplot", version.ref = "tablesaw" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
ai-rapids-cudf = { module = "ai.rapids:cudf", version.ref = "rapis" }
google-protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
tensorflow-core = { module = "org.tensorflow:tensorflow-core-api", version.ref = "tensorflowCore" }
wendykierp-jTransforms = { module = "com.github.wendykierp:JTransforms", version.ref = "jtransforms" }

antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlrRuntime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
testng = { module = "org.testng:testng", version.ref = "testng" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

