site_name: Deep Java Library
repo_name: deepjavalibrary/djl
repo_url: https://github.com/deepjavalibrary/djl/
site_url: https://djl.ai
use_directory_urls: false
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
theme:
  name: material
  logo: website/img/DJL.svg
  favicon: website/img/favicon.png
  features:
    - navigation.tabs
  palette:
    primary: light-blue
    accent: light-blue
  edit_uri: ''
google_analytics:
  - UA-159559852-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/deepjavalibrary/djl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deepjavalibrary
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/deepjavalibrary/shared_invite/zt-ar91gjkz-qbXhr1l~LFGEIEeGBibT7w
    - icon: fontawesome/brands/zhihu
      link: https://zhuanlan.zhihu.com/c_1255493231133417472
docs_dir: '../'
plugins:
  - search
  - mknotebooks
  - exclude:
      regex:
        - '.*\.(symbol|params|pt|jar|gz|zip|txt|json|sh|bat|cmd|puml|g4|java|py|cc|h|pro|properties|xml|gradlew|gradle|Dockerfile|RepositoryFactory|EngineProvider|ZooProvider)$|(docker|integration|testing|tools|docs/demos/apache-spark/notebook)/.*$'


nav:
  - Home:
      - Main: 'README.md'
      - 'docs/get.md'
      - 'docs/quick_start.md'
      - 'docs/README.md'
      - 'examples/README.md'
      - 'docs/interactive_tool.md'
      - Contributor Documentation:
          - Main: 'docs/development/README.md'
          - 'docs/development/setup.md'
          - 'docs/development/development_guideline.md'
          - 'docs/development/troubleshooting.md'
          - 'docs/development/dependency_management.md'
          - 'docs/development/add_model_to_model-zoo.md'
          - 'docs/development/add_dataset_to_djl.md'
      - 'docs/roadmap.md'
      - 'docs/faq.md'
  - Tutorials:
      - Beginner Tutorial:
          - 'jupyter/tutorial/01_create_your_first_network.ipynb'
          - 'jupyter/tutorial/02_train_your_first_model.ipynb'
          - 'jupyter/tutorial/03_image_classification_with_your_model.ipynb'
      - 'docs/d2l.md'
      - 'jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb'
      - 'jupyter/transfer_learning_on_cifar10.ipynb'
      - Load your own BERT:
          - BERT with MXNet: 'jupyter/mxnet/load_your_own_mxnet_bert.ipynb'
          - BERT with PyTorch: 'jupyter/pytorch/load_your_own_pytorch_bert.ipynb'
  - Guides:
      - 'docs/engine.md'
      - Models:
          - 'docs/load_model.md'
          - 'docs/model-zoo.md'
      - Datasets:
          - 'docs/dataset.md'
          - 'docs/development/how_to_use_dataset.md'
      - Inference and Production:
        - 'docs/create_serving_ready_model.md'
        - 'docs/development/configure_logging.md'
        - 'docs/how_to_collect_metrics.md'
        - 'docs/development/inference_performance_optimization.md'
        - 'extensions/benchmark/README.md'
        - 'docs/development/profiler.md'
      - 'docs/development/cache_management.md'
      - 'docs/development/memory_management.md'
      - 'docs/cv_utils.md'
  - DJL Community:
      - 'docs/forums.md'
      - 'leaders.md'
  - Apache MXNet:
      - Overview: 'engines/mxnet/README.md'
      - MXNet Engine: 'engines/mxnet/mxnet-engine/README.md'
      - MXNet Model Zoo: 'engines/mxnet/mxnet-model-zoo/README.md'
      - Import Gluon Model: 'docs/mxnet/how_to_convert_your_model_to_symbol.md'
      - Load a MXNet Model: 'jupyter/load_mxnet_model.ipynb'
      - Backend Optimizer for MXNet: 'docs/mxnet/mxnet_backend_optimizer.md'
  - PyTorch:
      - Overview: 'engines/pytorch/README.md'
      - PyTorch Engine: 'engines/pytorch/pytorch-engine/README.md'
      - PyTorch Model Zoo: 'engines/pytorch/pytorch-model-zoo/README.md'
      - Import PyTorch Model: 'docs/pytorch/how_to_convert_your_model_to_torchscript.md'
      - Load a PyTorch Model: 'jupyter/load_pytorch_model.ipynb'
  - TensorFlow:
      - Overview: 'engines/tensorflow/README.md'
      - TensorFlow Engine: 'engines/tensorflow/tensorflow-engine/README.md'
      - TensorFlow Model Zoo: 'engines/tensorflow/tensorflow-model-zoo/README.md'
      - Import TensorFlow Model: 'docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md'
      - Load a TensorFlow Model: 'jupyter/tensorflow/pneumonia_detection.ipynb'
  - Hybrid engines:
      - Hybrid engine overview: 'docs/hybrid_engine.md'
      - ONNX Runtime:
          - Overview: 'engines/onnxruntime/onnxruntime-engine/README.md'
          - Load a ONNX Model: 'jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb'
      - PaddlePaddle:
          - Overview: 'engines/paddlepaddle/README.md'
          - PaddlePaddle Engine: 'engines/paddlepaddle/paddlepaddle-engine/README.md'
          - PaddlePaddle Model Zoo: 'engines/paddlepaddle/paddlepaddle-model-zoo/README.md'
          - Import Paddle model:
              - English: 'docs/paddlepaddle/how_to_create_paddlepaddle_model.md'
              - 中文: 'docs/paddlepaddle/how_to_create_paddlepaddle_model_zh.md'
          - Facemask detection using PaddlePaddle:
              - English: 'jupyter/paddlepaddle/face_mask_detection_paddlepaddle.ipynb'
              - 中文: 'jupyter/paddlepaddle/face_mask_detection_paddlepaddle_zh.ipynb'
          - PaddleOCR example:
              - English: 'jupyter/paddlepaddle/paddle_ocr_java.ipynb'
              - 中文: 'jupyter/paddlepaddle/paddle_ocr_java_zh.ipynb'
      - TensorRT: 'engines/tensorrt/README.md'
      - TensorFlow Lite: 'engines/tflite/tflite-engine/README.md'
      - Neo DLR: 'engines/dlr/dlr-engine/README.md'
      - XGBoost: 'engines/ml/xgboost/README.md'
  - Extensions:
      - Android: 'android/README.md'
      - AWS S3 support: 'extensions/aws-ai/README.md'
      - fastText: 'extensions/fasttext/README.md'
      - Hadoop support: 'extensions/hadoop/README.md'
      - Huggingface Tokenizers: 'extensions/tokenizers/README.md'
      - OpenCV: 'extensions/opencv/README.md'
      - SentencePiece: 'extensions/sentencepiece/README.md'
      - Tablesaw: 'extensions/tablesaw/README.md'
      - DJL Serving:
          - 'docs/serving/README.md'
          - 'docs/serving/serving/docs/workflows.md'
          - 'docs/serving/serving/docs/configuration.md'
          - 'docs/serving/serving/docs/inference_api.md'
          - 'docs/serving/serving/docs/management_api.md'
          - 'docs/serving/serving/docs/plugin_management.md'
      - 'docs/serving/wlm/README.md'
  - Demos:
      - Demos: 'docs/demos/README.md'
      - AWS:
          - Amazon SageMaker:
              - Start with SageMaker: 'docs/demos/aws/sagemaker/README.md'
              - SageMaker Notebook: 'docs/demos/aws/sagemaker/notebook/README.md'
              - SageMaker Studio: 'docs/demos/aws/sagemaker/studio/README.md'
          - AWS-kinesis-video-streams: 'docs/demos/aws/aws-kinesis-video-streams/README.md'
          - Model Serving on AWS BeanStalk EC2: 'docs/demos/aws/beanstalk-model-serving/README.md'
          - AWS Lambda Serverless Model Serving with DJL: 'docs/demos/aws/lambda-model-serving/README.md'
          - AWS EMR:
              - Distributed inference: 'docs/demos/aws/emr-distributed-inference/dataprocess/README.md'
              - GPU Image Classification: 'docs/demos/aws/emr-distributed-inference/image-classification-gpu/README.md'
          - AWS Inferentia: 'docs/demos/aws/inferentia/README.md'
      - Android:
          - Doodledraw (PyTorch): 'docs/demos/android/pytorch_android/quickdraw_recognition/README.md'
          - Style Transfer (PyTorch): 'docs/demos/android/pytorch_android/style_transfer_cyclegan/README.md'
          - Face Detection (PyTorch): 'docs/demos/android/face_detection/README.md'
          - MXNet Android Template: 'docs/demos/android/mxnet-android/README.md'
      - EcoSystem:
          - Java Integrations:
              - DJL Component in Apache Camel: 'docs/demos/camel-djl/README.md'
              - Run TensorFlow model on GraalVM: 'docs/demos/graalvm/README.md'
              - Apache Spark Image Classification: 'docs/demos/apache-spark/image-classification/README.md'
              - Apache Beam CTR Prediction: 'docs/demos/apache-beam/ctr-prediction/README.md'
              - Apache Flink:
                  - Sentiment Analysis: 'docs/demos/apache-flink/sentiment-analysis/README.md'
                  - Sentence Encoding: 'docs/demos/apache-flink/sentence_embedding/README.md'
              - Apache Kafka Twitter Sentiment Analysis: 'docs/demos/apache-kafka/README.md'
              - Quarkus:
                  - DJL Extension for Quarkus: 'docs/demos/quarkus/extension/README.md'
                  - Integration without the Extension: 'docs/demos/quarkus/example/README.md'
      - Applications:
          - Footwear Classification: 'docs/demos/footwear_classification/README.md'
          - Live Object Detection: 'docs/demos/live-object-detection/README.md'
          - Pneumonia Detection: 'docs/demos/pneumonia-detection/README.md'
          - MultiEngine on DJL: 'docs/demos/development/multi-engine/README.md'
          - Interactive JShell and Block Runner for DJL: 'docs/demos/web-demo/interactive-console/README.md'
          - Malicious URL Detection: 'docs/demos/malicious-url-detector/README.md'
      - Extensions:
          - Visualizing Training with DJL: 'docs/demos/visualization-vue/README.md'
          - Interactive JShell and Block Runner for DJL: 'docs/demos/web-demo/interactive-console/README.md'


