name: MXNet Native OSX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Apache MXNet repository
        uses: actions/checkout@v2
        with:
          repository: apache/incubator-mxnet
          ref: v1.7.x
      - name: Install Dependencies
        run: |
          brew install nasm automake ninja libtool
      - name: Build
        run: |
          git --version
          clang --version
          CMAKE_STATICBUILD=1 ./tools/staticbuild/build.sh cpu
      - name: Upload libmxnet.dylib
        uses: actions/upload-artifact@v1
        with:
          name: libmxnet.dylib
          path: build/libmxnet.dylib
