name: Native S3 DLR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ macos-10.15 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get DLR_VERSION
        run: |
          DLR_VERSION="$(cat gradle.properties | awk -F '=' '/dlr_version/ {print $2}')"
          echo "DLR_VERSION=${DLR_VERSION}" >> $GITHUB_ENV
      - name: Checkout DLR repo
        uses: actions/checkout@v2
        with:
          repository: neo-ai/neo-ai-dlr
          ref: v${{ env.DLR_VERSION }}
          path: neo-ai-dlr
          submodules: 'recursive'
      - name: Build package
        run: |
          cd neo-ai-dlr
          mkdir build
          cd build
          CC=gcc-9 CXX=g++-9 cmake ..
          cmake --build . --config Release -- -j8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Upload native DJL to S3
        run: aws s3 cp *dlr.* s3://djl-ai/publish/dlr-${{ env.DLR_VERSION }}/native/osx/
        working-directory: neo-ai-dlr/build/lib
