name: Native S3 TFLite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-16.04]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorflow
          ref: 'v2.3.1'
          submodules: 'recursive'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: install Python Dependencies
        run: pip install numpy
      - name: build package
        run: |
          cd tensorflow
          bazel build -c opt //tensorflow/lite/java:tensorflowlitelib
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: upload to S3
        run: |
          mkdir -p jnilib/${{ runner.os }}
          cp bazel-bin/tensorflow/lite/java/libtensorflowlite_jni.so jnilib/${{ runner.os }}
          cp bazel-bin/tensorflow/lite/java/libtensorflowlitelib.jar jnilib
          aws s3 sync jnilib s3://djl-ai/publish/tflite-2.3.1/jnilib
