name: Serving publish

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'staging/snapshot, default is snapshot'
        required: true
        default: 'snapshot'
      repo-id:
        description: 'staging repository id for djl api packages'
        required: false
        default: ''

jobs:
  publish:
    if: github.repository == 'deepjavalibrary/djl'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: deepjavalibrary/djl-serving
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Enable gradle cache: https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish to snapshot repository
        if: ${{ github.event.inputs.mode == '' || github.event.inputs.mode == 'snapshot' }}
        run: ./gradlew publish -Psnapshot
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_ossrhPassword }}
          DJL_STAGING: ${{ github.event.inputs.repo-id }}
      - name: Publish to staging repository
        if: ${{ github.event.inputs.mode == 'staging' }}
        run: ./gradlew publish -Pstaging
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_ossrhPassword }}
          DJL_STAGING: ${{ github.event.inputs.repo-id }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Publish snapshot deb
        if: ${{ github.event.inputs.mode == '' || github.event.inputs.mode == 'snapshot' }}
        run: |
          ./gradlew :serving:createDeb -Psnapshot
          DJL_VERSION=$(cat gradle.properties | awk -F '=' '/djl_version/ {print $2}')
          aws s3 cp serving/build/distributions/*.deb s3://djl-ai/publish/djl-serving/
          aws cloudfront create-invalidation --distribution-id E371VB8JQ6NRVY --paths "/djl-serving/djl-serving_${DJL_VERSION}~SNAPSHOT*"
      - name: Publish release deb
        if: ${{ github.event.inputs.mode == 'staging' }}
        run: |
          ./gradlew :serving:createDeb -Pstaging
          DJL_VERSION=$(cat gradle.properties | awk -F '=' '/djl_version/ {print $2}')
          aws s3 cp serving/build/distributions/*.deb s3://djl-ai/publish/djl-serving/
          aws cloudfront create-invalidation --distribution-id E371VB8JQ6NRVY --paths "/djl-serving/djl-serving_${DJL_VERSION}*"
